name: tests


on:
  push:
    branches: [ master ]
  pull_requests:
    branches: [ master ]


jobs:


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v cmd/


    - name: Test
      run: go test -v ./...
